const rentalIncome = [
  { rentalIncome: [
    { month: 'January', rentalIncome: 1300 },
    { month: 'February', rentalIncome: 1650 },
    { month: 'March', rentalIncome: 1425 },
    { month: 'April', rentalIncome: 1900 },
    { month: 'May', rentalIncome: 1900 },
    { month: 'June', rentalIncome: 0 },
    { month: 'July', rentalIncome: 0 },
    { month: 'August', rentalIncome: 0 },
    { month: 'September', rentalIncome: 0 },
    { month: 'October', rentalIncome: 0 },
    { month: 'November', rentalIncome: 0 },
    { month: 'December', rentalIncome: 0 },
  ] },
  { rentalIncome: [
      { month: 'January', rentalIncome: 0 },
      { month: 'February', rentalIncome: 1100 },
      { month: 'March', rentalIncome: 1110 },
      { month: 'April', rentalIncome: 1200 },
      { month: 'May', rentalIncome: 1200 },
      { month: 'June', rentalIncome: 0 },
      { month: 'July', rentalIncome: 0 },
      { month: 'August', rentalIncome: 0 },
      { month: 'September', rentalIncome: 0 },
      { month: 'October', rentalIncome: 0 },
      { month: 'November', rentalIncome: 0 },
      { month: 'December', rentalIncome: 0 },
  ] },
  { rentalIncome: [
      { month: 'January', rentalIncome: 1350 },
      { month: 'February', rentalIncome: 870 },
      { month: 'March', rentalIncome: 1110 },
      { month: 'April', rentalIncome: 900 },
      { month: 'May', rentalIncome: 900 },
      { month: 'June', rentalIncome: 0 },
      { month: 'July', rentalIncome: 0 },
      { month: 'August', rentalIncome: 0 },
      { month: 'September', rentalIncome: 0 },
      { month: 'October', rentalIncome: 0 },
      { month: 'November', rentalIncome: 0 },
      { month: 'December', rentalIncome: 0 },
  ] },
  { rentalIncome: [
    { month: 'January', rentalIncome: 1250 },
    { month: 'February', rentalIncome: 1250 },
    { month: 'March', rentalIncome: 1300 },
    { month: 'April', rentalIncome: 1300 },
    { month: 'May', rentalIncome: 1300 },
    { month: 'June', rentalIncome: 0 },
    { month: 'July', rentalIncome: 0 },
    { month: 'August', rentalIncome: 0 },
    { month: 'September', rentalIncome: 0 },
    { month: 'October', rentalIncome: 0 },
    { month: 'November', rentalIncome: 0 },
    { month: 'December', rentalIncome: 0 },
  ] },
  { rentalIncome: [
      { month: 'January', rentalIncome: 0 },
      { month: 'February', rentalIncome: 0 },
      { month: 'March', rentalIncome: 1300 },
      { month: 'April', rentalIncome: 1300 },
      { month: 'May', rentalIncome: 1300 },
      { month: 'June', rentalIncome: 0 },
      { month: 'July', rentalIncome: 0 },
      { month: 'August', rentalIncome: 0 },
      { month: 'September', rentalIncome: 0 },
      { month: 'October', rentalIncome: 0 },
      { month: 'November', rentalIncome: 0 },
      { month: 'December', rentalIncome: 0 },
  ] },
  { rentalIncome: [
      { month: 'January', rentalIncome: 1000 },
      { month: 'February', rentalIncome: 1050 },
      { month: 'March', rentalIncome: 1110 },
      { month: 'April', rentalIncome: 1100 },
      { month: 'May', rentalIncome: 1100 },
      { month: 'June', rentalIncome: 0 },
      { month: 'July', rentalIncome: 0 },
      { month: 'August', rentalIncome: 0 },
      { month: 'September', rentalIncome: 0 },
      { month: 'October', rentalIncome: 0 },
      { month: 'November', rentalIncome: 0 },
      { month: 'December', rentalIncome: 0 },
  ] },
  { rentalIncome: [
      { month: 'January', rentalIncome: 1200 },
      { month: 'February', rentalIncome: 1200 },
      { month: 'March', rentalIncome: 0 },
      { month: 'April', rentalIncome: 1200 },
      { month: 'May', rentalIncome: 1200 },
      { month: 'June', rentalIncome: 0 },
      { month: 'July', rentalIncome: 0 },
      { month: 'August', rentalIncome: 0 },
      { month: 'September', rentalIncome: 0 },
      { month: 'October', rentalIncome: 0 },
      { month: 'November', rentalIncome: 0 },
      { month: 'December', rentalIncome: 0 },
  ] },
  { rentalIncome: [
      { month: 'January', rentalIncome: 1350 },
      { month: 'February', rentalIncome: 1350 },
      { month: 'March', rentalIncome: 1350 },
      { month: 'April', rentalIncome: 1350 },
      { month: 'May', rentalIncome: 1350 },
      { month: 'June', rentalIncome: 0 },
      { month: 'July', rentalIncome: 0 },
      { month: 'August', rentalIncome: 0 },
      { month: 'September', rentalIncome: 0 },
      { month: 'October', rentalIncome: 0 },
      { month: 'November', rentalIncome: 0 },
      { month: 'December', rentalIncome: 0 },
  ] },
];

module.exports = rentalIncome;
